### PR TITLE
Added Quizzes for Chapters

### PR DESCRIPTION
**Pull request by EvanZhouDev**

### CODE REVIEW

**Comment by EvanZhouDev** [comment]
This should be pretty much ready for merge.

**Comment by ThatXliner** [comment]
Will need content for later chapters. Mainly Amaar's.

**Comment by EvanZhouDev** [comment]
No, I do not want to get into the mess of cherrypicking or rebasing. It would be easier to merge right now and branch out and/or go directly into main later. It was a mistake in the first place to branch out for the quizzes.

**Comment by ThatXliner** [comment]
That’s true. Although some stylistic changes could be done (make it green for correct!), this looks fine. ~~Although I prefer daisyUI, we’re too close to deadline to do any nitpicking~~

**Pull request merged**
