### PR TITLE
Acts 21

### PR DESCRIPTION
**Pull request by DragonXDev**
People we must merge

### CODE REVIEW

**Comment by ThatXliner** [comment]
1. need quiz component
2. I don't understand last part...

**Comment by EvanZhouDev** [comment]
> 1. need quiz component

Will add after merged.
However, @DragonXDev still needs to fix the last part and _push it_

**Comment by ThatXliner** [comment]
@DragonXDev the whole reason i asked for the text is to flow better. I recommend reading the end of acts 20 and the beginning of 21 again. But *we can merge for now*

**Comment by DragonXDev** [comment]
Yes Evan I don't need italics to know to push my code; I'm not that Git illiterate, I just coded it.

> Will add after merged. However, @DragonXDev still needs to fix the last part and _push it_

**Pull request merged**
