### PR TITLE
Polish acts6

### PR DESCRIPTION
**Pull request by ThatXliner**
Going to add assets like an audience and stuff

### CODE REVIEW

**Comment by ThatXliner** [comment]
I used `opacity` and not `autoAlpha`. I don't really understand the point of `autoAlpha` since it doesn't help too much. Unless you tested it to work fine, I'd leave it as `opacity`

**Comment by EvanZhouDev** [comment]
Please add the quiz.

Then, I think it is good to merge.

**Review by EvanZhouDev — COMMENTED** [review]
- Undo dev mode
- Add quiz

Then, you are good for merge!

**Comment by ThatXliner** [comment]
@EvanZhouDev the quiz should be there...

**Pull request merged**
