### PR TITLE
Acts 13-20

### PR DESCRIPTION
**Pull request by ThatXliner**
- [x] Actual content
- [ ] ~~fix bug with timeline buttons when scrolling~~

### CODE REVIEW

**Comment by ThatXliner** [comment]
@EvanZhouDev, is it OK to have it with no scrolling animation?

**Comment by EvanZhouDev** [comment]
> @EvanZhouDev, is it OK to have it with no scrolling animation?

Sure, why not.

**Comment by ThatXliner** [comment]
ignore text for now

**Comment by ThatXliner** [comment]
I will enhance the content here since we are dropping the last section.

**Pull request merged**
